config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products do 
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_orgin, presence: true
  before_save(:titleize_product)

  scope :recently_added, -> { order(created_at: :desc).limit(3)}
  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(10)
  )}

  private 
    def titleize_product
      self.name = self.name.titleize
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates :content_body, length: { maximum: 250, minimum: 50 } 
  validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :is_admin?
  helper_method :current_user
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:index]
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :only => [:new, :create, :edit, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def index
    @products = Product.all
    if params[:g]
      render :list
    else
      @most_reviews = Product.most_reviews
      @recently_added = Product.recently_added
      render :index
    end
  end

  def list
    @products = Product.all
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else 
      render :new
    end
  end

  def edit 
    @product = Product.find(params[:id])
    render :edit
  end

  def show 
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to product_path
    else
      render :edit
    end
  end

  def destroy 
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "#{@product.name} has been destroyed."
    redirect_to products_path
  end


  private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_orgin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_action :only => [ :edit, :destroy] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end
  def create 
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else 
      render :new
    end
  end

  def show 
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy 
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end
  
private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
  <%= f.label :country_of_orgin %>
  <%= f.text_field :country_of_orgin %>
  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPrductReviewer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <% if user_signed_in? %>
      <h5><%= link_to "Home", products_path %></h5>
      <h5 class="text-right"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></h5>
    <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<h1 class="text-center" >Mario's Construction Material</h1>
<% if !user_signed_in? %>
  <p class="text-center" ><%= link_to "Sign In", new_user_session_path %></p>
  <p class="text-center" ><%= link_to "Sign Up", new_user_registration_path %></p>
<% else %>
  <p><%= link_to "see our products", products_path(:g => 'all') %></p>
  <% if @products.any? %>
    <h3 class="text-center" >our newest products</h3>
    <% @recently_added.each do |product| %>
      <div class="text-center"><%= link_to product.name, product_path(product) %></div>
    <% end %>
  <% else %>
    <p>There are no products with reviews yet.</p>
  <%end%>
  <% if @most_reviews.any? %>
  <h3> Our most talked about products</h3>
    <ul>
    <% @most_reviews.each do |most| %>
      <li><%= link_to most.name, product_path(most) %></li>
    <% end %>
  </ul>
  <%end%>
  
<% end %>

app/views/products/list.html.erb
<h1 class="text-center" >Our Products</h1>
 <% if current_user && current_user.admin %>
    <h4 class="text-center" >Welcome Admin</h4>
    <p class="text-center" ><%= link_to "Create a new product", new_product_path %></p>
  <% end %>
  <% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %>
    <% end %>
  </ul>
  <% else %>
    <p>There are no products at this time</p>
  <% end %>

app/views/products/new.html.erb
<h1> New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<h1 class="text-center mt-3 mb-3"><%= @product.name %></h1>
<div class="container">
<div>
  <div>
    <h3 class="text-right">Cost: $<%= @product.cost %>.00 </h3>
    <h3 class="mb-2">Origin: <%= @product.country_of_orgin %></h3>
  </div>
</div> 
</div>
<% if current_user && current_user.admin %>
  <p><%= link_to "Edit", edit_product_path(@product) %></p>
  <p><%= link_to "Delete", product_path(@product), :method => 'delete' %></p>
<% end %>

<p><%= link_to "Add Review", new_product_review_path(@product)%>



<%= render "reviews/reviews_partial" %>
<p>

app/views/reviews/_reviews_partial.html.erb
<% if @product.reviews.any? %>
    <h3>Reviews:</h3>
      <% @product.reviews.each do |review| %>
        <p>By: <b><%= review.author %></b></p>
        <p>Rating: <b><%= review.rating %></b> of <b>5</b></p>
        <p><%= review.content_body %></p>
        <% if current_user && current_user.admin %>
          <p><%= link_to "edit review", edit_product_review_path(@product, review) %></p>
        <% end %>
        <hr>
      <% end %>
      <p><%= link_to "add a review", new_product_review_path(@product) %></p>
    <% else %>
      <p>Sorry currently we have no reviews for this product</p>
    <% end %>

app/views/reviews/edit.html.erb
<h4>edit review for <%= @product.name %>:</h4>
<%= render "layouts/errors", :object => @review %>
<br>
<%= form_for [@product, @review] do |f| %>
  <input type="text" class ="form-control" name="review[author]" value="<%= @review.author %>">
  <br>
  <textarea type="text" class ="form-control" name="review[content_body]" rows="6" cols="50" ><%= @review.content_body %></textarea>
  <br>
  <input type="number" class ="form-control" name="review[rating]"  value="<%= @review.rating %>">
  <br>
  <button type="submit" class="btn btn-success">Edit</button>
<% end %>

app/views/reviews/new.html.erb
<h4>Write a review for <%= @product.name %>:</h4>
<%= render "layouts/errors", :object => @review %>
<br>
<%= form_for [@product, @review] do |f| %>
  <input type="text" class ="form-control" name="review[author]" placeholder="Your Name">
  <br>
  <textarea type="text" class ="form-control" name="review[content_body]" rows="6" cols="50" placeholder="How was this product? 250 charcters max"></textarea>
  <br>
  <input type="number" class ="form-control" name="review[rating]"  placeholder="Rate Product 1-5">
  <br>
  <button type="submit" class="btn btn-success">Submit!</button>
<% end %>